# Generated by Django 5.0.4 on 2026-02-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.URLField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("site", models.URLField()),
            ],
        ),
    ]
