# Generated by Django 5.0.4 on 2026-02-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="userregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
