# Generated by Django 5.0.4 on 2026-02-08 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0002_userregister"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userregister",
            old_name="first_name",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="userregister",
            old_name="last_name",
            new_name="lastname",
        ),
    ]
