# Generated by Django 5.0.4 on 2026-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0003_rename_first_name_userregister_firstname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="places",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="media")),
            ],
        ),
        migrations.DeleteModel(
            name="Place",
        ),
    ]
