# Generated by Django 5.0.4 on 2026-02-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0005_place_delete_places"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
