# Generated by Django 5.0.4 on 2026-02-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0007_food"),
    ]

    operations = [
        migrations.CreateModel(
            name="hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
