# Generated by Django 5.0.4 on 2026-02-13 13:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0008_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="desc",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="intro",
            field=models.TextField(blank=True, null=True),
        ),
    ]
