# Generated by Django 5.0.4 on 2026-02-13 14:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0009_place_desc_place_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="history",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
