# Generated by Django 5.0.4 on 2026-02-13 14:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0010_place_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="desc",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="history",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="History"
            ),
        ),
    ]
