# Generated by Django 5.0.4 on 2026-02-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0011_alter_place_desc_alter_place_history"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="intro",
            new_name="introduction",
        ),
        migrations.RemoveField(
            model_name="place",
            name="desc",
        ),
        migrations.AddField(
            model_name="place",
            name="content_fetched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="place",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="wiki_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
    ]
