# Generated by Django 5.0.4 on 2026-02-28 17:17

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0012_rename_intro_place_introduction_remove_place_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("review", models.TextField()),
                ("rating", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="place",
            name="content_fetched",
        ),
        migrations.RemoveField(
            model_name="place",
            name="location",
        ),
        migrations.RemoveField(
            model_name="place",
            name="wiki_url",
        ),
        migrations.AlterField(
            model_name="place",
            name="history",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="History"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="introduction",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Introduction"
            ),
        ),
    ]
