# Generated by Django 5.0.4 on 2026-03-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0013_review_remove_place_content_fetched_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="categories",
            field=models.ManyToManyField(related_name="places", to="guide.category"),
        ),
    ]
