# Generated by Django 5.0.4 on 2026-03-08 14:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0014_category_place_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="extra",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Extra"
            ),
        ),
    ]
