# Generated by Django 5.0.4 on 2026-03-15 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0017_placeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="guide.place",
            ),
        ),
    ]
