# Generated by Django 5.0.4 on 2026-03-17 10:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0019_wishlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Wishlist",
            new_name="Bucketlist",
        ),
    ]
