# Generated by Django 5.0.4 on 2026-03-17 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0020_rename_wishlist_bucketlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bucketlist",
            new_name="Wishlist",
        ),
    ]
