# Generated by Django 5.0.4 on 2026-03-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0021_rename_bucketlist_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="guide.place",
            ),
        ),
    ]
