# Generated by Django 5.0.4 on 2026-03-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0028_alter_wishlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="category",
            field=models.CharField(
                choices=[("Tourist", "Tourist"), ("Business Owner", "Business Owner")],
                default="Tourist",
                max_length=50,
            ),
        ),
    ]
