# Generated by Django 5.0.4 on 2026-04-05 10:37

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0029_userregister_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
                ("address", models.TextField()),
                ("menu", models.FileField(blank=True, null=True, upload_to="menus/")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "foods",
                    models.ManyToManyField(related_name="shops", to="guide.food"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="review",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="guide.shop",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="guide.shop",
            ),
        ),
        migrations.CreateModel(
            name="ShopImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="guide.shop",
                    ),
                ),
            ],
        ),
    ]
