# Generated by Django 5.0.4 on 2026-04-07 12:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0030_shop_review_shop_wishlist_shop_shopimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
    ]
