# Generated by Django 5.0.4 on 2026-04-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0031_food_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="guide.userregister",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotels",
                to="guide.userregister",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="guide.userregister",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="guide.userregister",
            ),
        ),
    ]
