# Generated by Django 5.0.4 on 2026-04-09 17:08

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0032_food_owner_hotel_owner_place_owner_shop_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="menu",
        ),
        migrations.AlterField(
            model_name="shop",
            name="foods",
            field=models.ManyToManyField(
                blank=True, related_name="shops", to="guide.food"
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="guide.userregister",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shop",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="guide.product"
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="guide.product",
                    ),
                ),
            ],
        ),
    ]
