# Generated by Django 5.0.4 on 2026-04-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0033_remove_place_owner_remove_shop_menu_alter_shop_foods_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shop",
            unique_together={("owner", "title")},
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="guide.hotel",
                    ),
                ),
            ],
        ),
    ]
