# Generated by Django 5.0.4 on 2026-04-09 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0034_alter_shop_unique_together_hotelimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotelimage",
            old_name="product",
            new_name="hotel",
        ),
    ]
