# Generated by Django 5.0.4 on 2026-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0035_rename_product_hotelimage_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="shops", to="guide.product"
            ),
        ),
    ]
