# Generated by Django 5.0.4 on 2026-04-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0036_alter_shop_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="product",
            name="owner",
        ),
        migrations.AddField(
            model_name="food",
            name="owners",
            field=models.ManyToManyField(
                blank=True, related_name="foods", to="guide.userregister"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="owners",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="guide.userregister"
            ),
        ),
    ]
