# Generated by Django 5.0.4 on 2026-04-13 08:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0037_remove_food_owner_remove_product_owner_food_owners_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
    ]
