# Generated by Django 5.0.4 on 2026-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0041_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="itinerary",
            name="user",
        ),
        migrations.RemoveField(
            model_name="itineraryday",
            name="itinerary",
        ),
        migrations.RemoveField(
            model_name="itineraryitem",
            name="day",
        ),
        migrations.RemoveField(
            model_name="itineraryitem",
            name="food",
        ),
        migrations.RemoveField(
            model_name="itineraryitem",
            name="hotel",
        ),
        migrations.RemoveField(
            model_name="itineraryitem",
            name="place",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="Itinerary",
        ),
        migrations.DeleteModel(
            name="ItineraryDay",
        ),
        migrations.DeleteModel(
            name="ItineraryItem",
        ),
    ]
