# Generated by Django 5.0.4 on 2026-04-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0043_newslettersubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("temperature", models.FloatField()),
                ("feels_like", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("wind_speed", models.FloatField()),
                ("description", models.CharField(max_length=100)),
                ("icon_class", models.CharField(max_length=50)),
                ("background", models.CharField(max_length=100)),
                ("sunrise", models.TimeField()),
                ("sunset", models.TimeField()),
                ("current_date", models.CharField(max_length=50)),
                ("current_time", models.CharField(max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("place", "Place"),
                            ("food", "Food"),
                            ("hotel", "Hotel"),
                        ],
                        max_length=10,
                    ),
                ),
                ("item_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("avg_rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guide.userregister",
                    ),
                ),
            ],
        ),
    ]
