# Generated by Django 5.0.4 on 2026-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0044_weatherdata_recommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("place", "Place"),
                    ("food", "Food"),
                    ("hotel", "Hotel"),
                    ("shop", "Shop"),
                    ("product", "Product"),
                ],
                max_length=10,
            ),
        ),
    ]
