# Generated by Django 5.0.4 on 2026-04-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0048_cabbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="cabbooking",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
