# Generated by Django 5.0.4 on 2026-04-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0049_cabbooking_razorpay_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabbooking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="guide.userregister"
            ),
        ),
    ]
