# Generated by Django 5.0.4 on 2026-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0050_alter_cabbooking_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.AddField(
            model_name="cabbooking",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
