# Generated by Django 5.0.4 on 2026-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0051_delete_payment_cabbooking_razorpay_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(related_name="product", to="guide.category"),
        ),
    ]
