# Generated by Django 5.0.4 on 2026-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0052_product_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="categories",
            field=models.ManyToManyField(related_name="food", to="guide.category"),
        ),
    ]
