# Generated by Django 5.0.4 on 2026-04-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0053_food_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="categories",
            field=models.ManyToManyField(related_name="hotel", to="guide.category"),
        ),
    ]
