# Generated by Django 5.0.4 on 2026-04-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0054_hotel_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="categories",
            field=models.ManyToManyField(related_name="shop", to="guide.category"),
        ),
    ]
