# Generated by Django 5.0.4 on 2026-05-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0056_restaurant_restaurantimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="alternate_contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="newsletter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userregister",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="userregister",
            name="social_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
