# Generated by Django 5.0.4 on 2026-05-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0057_userregister_address_userregister_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="guide.userregister"
            ),
        ),
    ]
