# Generated by Django 5.0.4 on 2026-05-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0058_alter_newslettersubscriber_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregister",
            name="lastname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
