# Generated by Django 5.0.4 on 2026-05-13 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0060_alter_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="guide.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="guide.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("place", "Place"),
                    ("food", "Food"),
                    ("hotel", "Hotel"),
                    ("shop", "Shop"),
                    ("product", "Product"),
                    ("restaurant", "Restaurant"),
                ],
                max_length=10,
            ),
        ),
    ]
