# Generated by Django 5.0.4 on 2026-05-14 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0061_review_restaurant_wishlist_restaurant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField()),
                ("image", models.ImageField(upload_to="hotel_branches/")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="guide.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelBranchImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hotel_branch_gallery/")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="guide.hotelbranch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address", models.TextField()),
                ("image", models.ImageField(upload_to="restaurant_branches/")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="guide.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantBranchImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="restaurant_branch_gallery/")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="guide.restaurantbranch",
                    ),
                ),
            ],
        ),
    ]
