# Generated by Django 5.0.4 on 2026-05-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guide", "0063_backfill_main_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
